apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nodejs-app
  template:
    metadata:
      labels:
        app: my-nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: deveshrathore13/nodejs-dynamic-website:v1.0
        ports:
        - containerPort: 4000
